name: Fetch API and Save as JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read JSON file
        id: read-json
        run: echo "::set-output name=data::$(cat api_response.json | jq -r .data)"

      - name: Update README
        run: |
          sed -i "s|{{IMAGE_SRC}}|${{ steps.read-json.outputs.data }}|g" TEST.md

  fetch-and-save-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch from API and Save as JSON
      run: |
        API_URL="https://random-ka-v2.onrender.com"
        RESPONSE=$(curl -s $API_URL)

        # Guardar la respuesta en un archivo JSON
        echo "$RESPONSE" > api_response.json

        # Puedes imprimir la respuesta o realizar otras operaciones según tus necesidades
        echo "API Response: $RESPONSE"

    - name: Commit and Push Changes
      run: |
        git config --local user.email "6327@holbertonstudents.com"
        git config --local user.name "${GITHUB_ACTOR}"
        git add api_response.json
        git commit -m "Update API response"
        git push
